<?php
    $customer = Mage::getModel('customer/session')->getCustomer();
    $profile = $this->getProfileCustomer();
    if($customer && $customer->getId()){
         $relation = Mage::getModel('friend/relation')->getCollection()
             ->addFieldToFilter('inviter_id',$customer->getId())
             ->addFieldToFilter('target_id',$profile->getId())
             ->getFirstItem();
    }
?>
<?php if($customer->getId()!=$profile->getId()):?>
<div class="box">
    <?php if($relation && $relation->getStatus()==1):?>
        <a href="<?php echo Mage::getBaseUrl().'friend/relation/remove/inviter/'.$customer->getId().'/target/'.$profile->getId()?>">
            <?php echo $this->__('Remove This Friend.')?>
        </a>
    <?php else:?>
        <a href="<?php echo Mage::getBaseUrl().'friend/relation/remove/inviter/'.$customer->getId().'/target/'.$profile->getId()?>"><?php echo $this->__('Send Friend Request.') ?></a>
    <?php endif;?>
</div>
<?php endif;?>
<div class="col2-set">
    <div class="box">
        <div class="col-1">
            <div class="box-content">
                <?php echo $this->getLayout()->createBlock('profileimage/header_profileimage')->setTemplate('profileimage/profile/image.phtml')->toHtml();?>
            </div>
        </div>
        <div class="col-2">
            <div class="box-content">
                <p>
                    <?php echo $this->escapeHtml($profile->getDisplayName()) ?><br/>
                    <?php echo $this->escapeHtml($profile->getName()) ?><br/>
                    <?php if($profile->getGender()):?>
                    <?php echo $this->__(Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getOptionText($profile->getGender()))?>
                    <?php endif;?>
                    <br/>
                    <?php if($profile->getDob()):?>
                    <?php echo date("F j, Y",strtotime($profile->getDob())) ?><br/>
                    <?php endif;?>
                    <?php echo $this->escapeHtml($profile->getEmail()) ?><br/>
                    <?php $addresses = $profile->getAddresses()?>
                    <?php if(count($addresses)):?>
                    <?php foreach ($addresses as $address):?>
                        <address>
                            <?php echo $this->render($address)?>
                        </address>
                        <?php break;?>
                        <?php endforeach;?>
                    <?php endif;?>
                </p>
            </div>
        </div>
    </div>
</div>
    <div id="profile-friends">
        <?php echo $this->getLayout()->createBlock('friend/list')->setTemplate('profile/friend/list.phtml')->toHtml() ?>
    </div>
<div id="profile-reviews">
    <?php echo $this->getLayout()->createBlock('review/customer_list')->setTemplate('profile/review/list.phtml')->toHtml() ?>
</div>
    <div id="profile-wishlist">
        <?php echo $this->getChildHtml('profile.wishlist') ?>
    </div>
<div class="back-button">
    <button onclick="history.back();" class="button" title="<?php echo $this->__('Back') ?>" type="button">
        <span>
            <span><?php echo $this->__('Back') ?></span>
        </span>
    </button>
</div>