<div class="col2-set">
    <div class="box">
        <div class="col-1">
            <div class="box-content">
                <?php echo $this->getLayout()->createBlock('profileimage/header_profileimage')->setTemplate('profileimage/profile/image.phtml')->toHtml();?>
            </div>
        </div>
        <div class="col-2">
            <div class="box-content">
                <p>
                    <?php echo $this->escapeHtml($this->getProfileCustomer()->getDisplayName()) ?><br/>
                    <?php echo $this->escapeHtml($this->getProfileCustomer()->getName()) ?><br/>
                    <?php if($this->getProfileCustomer()->getGender()):?>
                    <?php echo $this->__(Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getOptionText($this->getProfileCustomer()->getGender()))?>
                    <?php endif;?>
                    <br/>
                    <?php if($this->getProfileCustomer()->getDob()):?>
                    <?php echo date("F j, Y",strtotime($this->getProfileCustomer()->getDob())) ?><br/>
                    <?php endif;?>
                    <?php echo $this->escapeHtml($this->getProfileCustomer()->getEmail()) ?><br/>
                    <?php $addresses = $this->getProfileCustomer()->getAddresses()?>
                    <?php if(count($addresses)):?>
                    <?php foreach ($addresses as $address):?>
                        <address>
                            <?php echo $this->render($address)?>
                        </address>
                        <?php break;?>
                        <?php endforeach;?>
                    <?php endif;?>
                </p>
            </div>
        </div>
    </div>
</div>
<div id="profile-reviews">
    <?php echo $this->getLayout()->createBlock('review/customer_list')->setTemplate('profile/review/list.phtml')->toHtml() ?>
</div>
    <div id="profile-wishlist">
        <?php echo $this->getChildHtml('profile.wishlist') ?>
    </div>
<div class="back-button">
    <button onclick="history.back();" class="button" title="<?php echo $this->__('Back') ?>" type="button">
        <span>
            <span><?php echo $this->__('Back') ?></span>
        </span>
    </button>
</div>