<div class="box">
    <div class="col-2">
        <div class="box-title">
            <h3><?php echo $this->__('My Friends') ?></h3>
        </div>
        <div class="box-content">
            <?php $friends = $this->getFriends()?>
            <?php if(count($friends)):?>
            <ul>
                <?php foreach ($friends as $friendId):?>
                <li class="friends-list">
                    <?php $friend = Mage::getModel('customer/customer')->load($friendId)?>
                    <?php
                        if($friend->getDisplayName()){
                            $name = $friend->getDisplayName();
                        }else{
                            $name = $friend->getName();
                        }
                    ?>
                    <a href="<?php echo $this->getUrl('customer/account/profile').'profile_id/'.$friendId?>" class="friend-list">
                        <?php $src = $this->getUrl('profileimage/customer/viewProfileimage',array('id'=>$friendId))?>
                        <img style="margin-right:10px; width:20px;" src=<?php echo $src?>/><span class="display-name"><?php echo $name?><span>
                    </a>
                    <button style="margin-left:10px;" value="<?php echo $friend->getId()?>" class="button send-message-button"><span><span><?php echo $this->__('Send private message')?></span></span></button>
                </li>
                <?php endforeach ?>
            </ul>
            <?php else:?>
                <p><?php echo $this->__('You have not add any friend.') ?></p>
            <?php endif;?>
            <div class="fieldset">
                <a href="<?php echo Mage::getBaseUrl().'friend/relation/search'?>"><?php echo $this->__('Find friends')?></a>
            </div>
        </div>
    </div>
</div>
<div id="quickview-cache" style="display:none">
    <a id="fancybox-anchor" href="#send-friend-form">This is the anchor for fancybox.</a>
    <div id="send-friend-form"></div>
</div>
<script type="text/javascript">
    jQuery('.send-message-button').click(function(){
        var to = jQuery(this).val();
        jQuery.ajax({
            url: "<?php echo $this->getUrl('message/message/ajax').'?to='?>"+to
        }).done(function(data) {
                    jQuery('#send-friend-form').html(data);
                    jQuery("#fancybox-anchor").fancybox();
                    jQuery("#fancybox-anchor").click();
                })
    })
</script>
