<script type="text/javascript">
    $j = jQuery.noConflict();
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function(e) {
                $j('#preview').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }

</script>

<form action="<?php echo $this->getUploadUrl() ?>" method="post" enctype="multipart/form-data" >
        <ul class="form-list">
            <li>
                <?php if ($this->getProfileimage()): ?>
                <div class="profileimage-wrapper">
                    <img id="preview" src="<?php if ($this->getProfileimage()) { echo $this->getProfileimagePath();}?>" width="160"/>
                </div>
                <?php endif ?>
            </li>
            <li> 
                <input type="file" name="profileimage-file" id="file" onChange="readURL(this);"><br>
            </li>
            <li>
                <button type ="submit" name="submit" title="upload" class="button">
                    <span><span><?php echo $this->__('Upload') ?></span></span>
                </button>
            </li>
        </ul>
</form>