<div id="home-google-map"></div>
<script type="text/javascript">
    var map;
    function initialize() {
        var mapOptions = {
            zoom: 15
        };
        map = new google.maps.Map(document.getElementById('home-google-map'),
                mapOptions);

        // Try HTML5 geolocation
        if(navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                var pos = new google.maps.LatLng(position.coords.latitude,
                        position.coords.longitude);

                var marker = new google.maps.Marker({
                    position: pos,
                    title:"Current Location"
                });
                marker.setMap(map);
                map.setCenter(pos);
            }, function() {
                handleNoGeolocation(true);
            });
        } else {
            // Browser doesn't support Geolocation
            handleNoGeolocation(false);
        }
    }

    function handleNoGeolocation(errorFlag) {
        if (errorFlag) {
            var content = 'Error: The Geolocation service failed.';
        } else {
            var content = 'Error: Your browser doesn\'t support geolocation.';
        }

        var marker = new google.maps.Marker({
            position: new google.maps.LatLng(34.05, -118.25),
            title:"Los Angeles"
        });
        marker.setMap(map);
    }

    google.maps.event.addDomListener(window, 'load', initialize);
</script>
